# Created by:	Eric Turgeon ericturgeon@ghostbsd.org
# Date created:	November 11 2013


PORTNAME=	station-tweak
PORTVERSION=	0.1
PORTREVISION=	0
CATEGORIES=	net-mgmt
MASTER_SITES=	https://github.com/GhostBSD/${PORTNAME}/archive/

MAINTAINER=	ericturgeon@ghostbsd.org
COMMENT=	Mate configuration system.

LICENSE=	BSD

USE_GITHUB=	yes
GH_ACCOUNT=	GhostBSD

USES = python:2
USE_PYTHON=	distutils
USE_GNOME=	pygtk2

.include <bsd.port.mk>
