#!/bin/sh

restore_freebsd()
{
    # restore from backup original freebsd files
    cp -af /usr/local/share/ghostbsd/common-live-settings/base/backup/* /
}

restore_packages_settings()
{
    # revert sudoers hack
    if [ -x /usr/local/bin/sudo ]; then
        sed -i "" "s@%wheel ALL=(ALL) ALL@# %wheel ALL=(ALL) ALL@" /usr/local/etc/sudoers
        sed -i "" "s@%sudo	ALL=(ALL) ALL@# %sudo	ALL=(ALL) ALL@" /usr/local/etc/sudoers
    fi

    update-alternatives --altdir /usr/local/etc/alternatives --remove htmlview /usr/local/bin/firefox
}

remove_files_from()
{
    for files in $(ls /usr/local/share/ghostbsd/common-live-settings/etc/rc.d); do
        rm -f /etc/rc.d/$files
    done
}

autologin_revert()
{
# removing auto login, startx and X configuration.
( echo "g/# ghostbsd user autologin/d" ; echo 'wq' ) | ex -s /etc/gettytab
( echo "g/ghostbsd:\\/d" ; echo 'wq' ) | ex -s /etc/gettytab
( echo "g/:al=ghostbsd:ht:np:sp#115200:/d" ; echo 'wq' ) | ex -s /etc/gettytab
sed -i "" "/ttyv0/s/ghostbsd/Pc/g" /etc/ttys
sed -i '' 's@#pcdm_enable="YES"@pcdm_enable="YES"@g' /etc/rc.conf

# Removing livecd hostname.
( echo 'g/hostname="livecd"/d' ; echo 'wq' ) | ex -s /etc/rc.conf
}
case $2 in
    DEINSTALL)
    restore_freebsd
    restore_packages_settings
    remove_files_from
#    autologin_revert
    ;;
    POST-DEINSTALL)
    #rm -Rf /usr/local/share/ghostbsd/common-live-settings/
    echo "ghostbsd-live-common-settings was uninstalled."
    ;;
    *)
    echo $2
    ;;
esac

exit 0

