#!/bin/sh

backup_freebsd()
{
    # backup files from etc
  for tocopy in $(ls /usr/local/share/ghostbsd/common-live-settings/base/override/etc/rc.d) ; do
    if [ -f /etc/rc.d/$tocopy ]; then
      cp -af /etc/rc.d/$tocopy /usr/local/share/ghostbsd/common-live-settings/base/backup/etc/rc.d/
    fi
  done
}

freebsd_overrides()
{
  cp -af /usr/local/share/ghostbsd/common-live-settings/base/override/* /
}

copy_files_in()
{
    cp -af /usr/local/share/ghostbsd/common-live-settings/etc/* /etc
}


case "$2" in
    POST-INSTALL)
    # backup old files from FreeBSD base system
    backup_freebsd
    # copy files from override to FreeBSD base system
    freebsd_overrides
    # copy files from base/etc to etc
    copy_files_in
    ;;
    *)
    ;;
esac

exit 0


