#!/bin/sh

case "$2" in
    PRE-INSTALL)
    if [ ! -d /usr/local/share/glib-2.0/schemas ] ; then
        mkdir -p /usr/local/share/glib-2.0/schemas
    fi
    ;;
    POST-INSTALL)
    # copy dmrc from ghostbsd dir to /usr/share/skel
    cp -af /usr/local/share/ghostbsd/gnome-installed-settings/etc/skel/dmrc /usr/share/skel/dot.dmrc
    
    # copy grub config 
    if [ ! -d /usr/local/etc/default ]; then
        mkdir -p /usr/local/etc/default
    fi
    cp -af /usr/local/share/ghostbsd/gnome-installed-settings/etc/default/*   /usr/local/etc/default
    
    #copy local policy 
    if [ ! -d /usr/local/etc/polkit-1 ]; then
        mkdir -p /usr/local/etc/polkit-1
    fi
    cp -af /usr/local/share/ghostbsd/gnome-installed-settings/etc/polkit-1/* /usr/local/etc/polkit-1

    # compile schemas
    glib-compile-schemas /usr/local/share/glib-2.0/schemas
    
    # set x-terminal-emulator alternative for gksu
    if [ -e /usr/local/bin/gnome-terminal ] ; then
        update-alternatives --altdir /usr/local/etc/alternatives --install /usr/local/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/gnome-terminal 50
    fi

    # User gtk-bookmarks.
    printf "file:///root/Documents Documents
file:///root/Downloads Downloads
file:///root/Movies Movies
file:///root/Music Music
file:///root/Pictures Pictures
" > /root/.gtk-bookmarks

    mkdir -p /root/Documents
    mkdir -p /root/Downloads
    mkdir -p /root/Movies
    mkdir -p /root/Music
    mkdir -p /root/Pictures

    printf "file:///home/ghostbsd/Documents Documents
file:///home/ghostbsd/Downloads Downloads
file:///home/ghostbsd/Movies Movies
file:///home/ghostbsd/Music Music
file:///home/ghostbsd/Pictures Pictures
" > /home/ghostbsd/.gtk-bookmarks

    chmod g+rwx /home/ghostbsd/.gtk-bookmarks
    mkdir -p /home/ghostbsd/Documents
    chmod g+rwx /home/ghostbsd/Documents
    mkdir -p /home/ghostbsd/Downloads
    chmod g+rwx /home/ghostbsd/Downloads
    mkdir -p /home/ghostbsd/Movies 
    chmod g+rwx /home/ghostbsd/Movies
    mkdir -p /home/ghostbsd/Music
    chmod g+rwx /home/ghostbsd/Music
    mkdir -p /home/ghostbsd/Pictures
    chmod g+rwx /home/ghostbsd/Pictures
    ;;
esac

exit 0
