#!/bin/sh

case "$2" in
    POST-INSTALL)
    # copy dmrc from ghostbsd dir to /usr/share/skel
    cp -af /usr/local/share/ghostbsd/xfce-installed-settings/etc/skel/dmrc /usr/share/skel/dot.dmrc

    # copy gtkrc-2.0 from ghostbsd dir to /usr/share/skel
    cp -af /usr/local/share/ghostbsd/xfce-installed-settings/etc/skel/gtkrc-2.0 /usr/share/skel/dot.gtkrc-2.0
    
    # copy grub config 
    if [ ! -d /usr/local/etc/default ]; then
        mkdir -p /usr/local/etc/default
    fi
    cp -af /usr/local/share/ghostbsd/xfce-installed-settings/etc/default/*   /usr/local/etc/default

    # copy xdg
    cp -af /usr/local/share/ghostbsd/xfce-installed-settings/etc/xdg/*   /usr/local/etc/xdg
    
    # set x-terminal-emulator alternative for gksu
    if [ -e /usr/local/bin/xfce4-terminal ] ; then
        update-alternatives --altdir /usr/local/etc/alternatives --install /usr/local/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/xfce4-terminal 50
    fi

    # User gtk-bookmarks.
    printf "file:///root/Documents Documents
file:///root/Downloads Downloads
file:///root/Movies Movies
file:///root/Music Music
file:///root/Pictures Pictures
" > /root/.gtk-bookmarks

    mkdir -p /root/Documents
    mkdir -p /root/Downloads
    mkdir -p /root/Movies
    mkdir -p /root/Music
    mkdir -p /root/Pictures

    printf "file:///home/ghostbsd/Documents Documents
file:///home/ghostbsd/Downloads Downloads
file:///home/ghostbsd/Movies Movies
file:///home/ghostbsd/Music Music
file:///home/ghostbsd/Pictures Pictures
" > /home/ghostbsd/.gtk-bookmarks

    chmod g+rwx /home/ghostbsd/.gtk-bookmarks
    mkdir -p /home/ghostbsd/Documents
    chmod g+rwx /home/ghostbsd/Documents
    mkdir -p /home/ghostbsd/Downloads
    chmod g+rwx /home/ghostbsd/Downloads
    mkdir -p /home/ghostbsd/Movies 
    chmod g+rwx /home/ghostbsd/Movies
    mkdir -p /home/ghostbsd/Music
    chmod g+rwx /home/ghostbsd/Music
    mkdir -p /home/ghostbsd/Pictures
    chmod g+rwx /home/ghostbsd/Pictures
    ;;
esac

exit 0
