#!/bin/sh

restore_freebsd()
{
    # restore from backup original freebsd files
    cp -af /usr/local/share/ghostbsd/common-installed-settings/base/backup/* /

    if [ ! -f /usr/local/share/ghostbsd/common-installed-settings/base/backup/boot/splash.pcx ]; then
        rm -f /boot/splash.pcx
    fi

    for files in rc.local make.conf devfs.rules ; do
        if [ ! -f /usr/local/share/ghostbsd/common-installed-settings/base/backup/etc/$files ]; then
            rm -f /etc/$files
        fi
    done

    # removes virtualbox init script
    if [ -f /etc/rc.d/virtualbox ]; then
        rm -f /etc/rc.d/virtualbox
    fi

    # restore from original packages files
    if [ -d /usr/local/share/ghostbsd/common-installed-settings/packages/backup/etc ] ; then
        cp -af /usr/local/share/ghostbsd/common-installed-settings/packages/backup/etc/* /etc
    fi
    if [ -d /usr/local/share/ghostbsd/common-installed-settings/packages/backup/applications ];then
        cp -af /usr/local/share/ghostbsd/common-installed-settings/packages/backup/applications/* \
    /usr/local/share/applications
    fi
}

rem_filesfrom_freebsd()
{
    # removes X config files
    for files in $(ls /usr/local/share/ghostbsd/common-installed-settings/packages/override/etc/X11 ) ; do
        rm -f /etc/X11/$files
    done
}

restore_packages_settings()
{
    # removes htmlview alternative for cups
    update-alternatives --altdir /usr/local/etc/alternatives --remove htmlview /usr/local/bin/firefox
}

case $2 in
    DEINSTALL)
    restore_freebsd
    rem_filesfrom_freebsd
    restore_packages_settings
    ;;
    POST-DEINSTALL)
    #rm -Rf /usr/local/share/ghostbsd/common-installed-settings/
    echo "ghostbsd-installed-common-settings was uninstalled."
    ;;
    *)
    echo $2
    ;;
esac

exit 0
