#!/bin/sh

[ "$2" = 'POST-DEINSTALL' ] || exit 0

# revert to original freebsd schemas
if [ -d /usr/local/share/glib-2.0/schemas ] ; then
     glib-compile-schemas /usr/local/share/glib-2.0/schemas
fi

# removes x-terminal-alternative needed for gksu
if [ -e /usr/local/bin/mate-terminal ] ; then
    update-alternatives --altdir /usr/local/etc/alternatives --remove x-terminal-emulator /usr/local/bin/mate-terminal
fi

# reverts mate panel layout
 mv /usr/local/share/mate-panel/layouts/mate.layout /usr/local/share/mate-panel/layouts/default.layout

exit 0
