#!/bin/sh

case "$2" in
    PRE-INSTALL)
    if [ ! -d /usr/local/share/glib-2.0/schemas ] ; then
        mkdir -p /usr/local/share/glib-2.0/schemas
    fi
    ;;
    POST-INSTALL)
    # copy dmrc from ghostbsd dir to /usr/share/skel
    cp -af /usr/local/share/ghostbsd/mate-installed-settings/etc/skel/dmrc /usr/share/skel/dot.dmrc
    
    # copy grub config 
    if [ ! -d /usr/local/etc/default ]; then
        mkdir -p /usr/local/etc/default
    fi
    cp -af /usr/local/share/ghostbsd/mate-installed-settings/etc/default/*   /usr/local/etc/default
    
    #copy local policy 
    if [ ! -d /usr/local/etc/polkit-1 ]; then
        mkdir -p /usr/local/etc/polkit-1
    fi
    cp -af /usr/local/share/ghostbsd/mate-installed-settings/etc/polkit-1/* /usr/local/etc/polkit-1
    
    # overrite mate terminal xml for transparency
    mv /usr/local/share/glib-2.0/schemas/org.mate.terminal.gschema.xml /usr/local/share/ghostbsd/mate-installed-settings/schemas/org.mate.terminal.gschema.xml.old
    cp -af /usr/local/share/ghostbsd/mate-installed-settings/schemas/org.mate.terminal.gschema.xml /usr/local/share/glib-2.0/schemas
    
    # compile schemas
    glib-compile-schemas /usr/local/share/glib-2.0/schemas
    
    # set x-terminal-emulator alternative for gksu
    if [ -e /usr/local/bin/mate-terminal ] ; then
        update-alternatives --altdir /usr/local/etc/alternatives --install /usr/local/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/mate-terminal 50
    fi
    
    # overwrite default mate panel
    if [ ! -d /usr/local/share/mate-panel/layouts ]; then
        mkdir -p /usr/local/share/mate-panel/layouts
    fi
    mv /usr/local/share/mate-panel/layouts/default.layout /usr/local/share/mate-panel/layouts/mate.layout
    cp -af /usr/local/share/ghostbsd/mate-installed-settings/mate-panel/panel-default-layout.mate /usr/local/share/mate-panel/layouts/default.layout
    ;;
esac

exit 0
