PORTNAME=	certifi
PORTVERSION=	2023.7.22
PORTREVISION=	1
CATEGORIES=	security python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Mozilla SSL certificates
WWW=		https://github.com/certifi/python-certifi

LICENSE=	MPL20

USES=		python
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include "${.CURDIR}/Makefile.ca"

.include <bsd.port.mk>
