#!/bin/sh

[ "$2" = 'POST-INSTALL' ] || exit 0

if [ -e /usr/local/bin/gnome-terminal ] ; then
    update-alternatives --altdir /usr/local/etc/alternatives --install /usr/local/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/gnome-terminal 50
fi

if [ -e /usr/local/bin/lxterminal ] ; then
     update-alternatives --altdir /usr/local/etc/alternatives --install /usr/local/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/lxterminal 50
fi

# put ghostbsd-irc to desktop
cp -af /usr/local/share/applications/ghostbsd-irc.desktop /home/ghostbsd/Desktop
chmod +x /home/ghostbsd/Desktop/ghostbsd-irc.desktop
#chown -R 1000:0 /home/ghostbsd/Desktop/ghostbsd-irc.desktop

exit 0
