# Created by:	Eric Turgeon ericturgeon@ghostbsd.org
# Date created:	November 11 2013


PORTNAME=	networkmgr
PORTVERSION=	0.3
PORTREVISION=	0
CATEGORIES=	net-mgmt
MASTER_SITES=	https://github.com/GhostBSD/${PORTNAME}/archive/

MAINTAINER=	ericturgeon@ghostbsd.org
COMMENT=	GTK network manager.

LICENSE=	BSD

USE_GITHUB=	yes
GH_ACCOUNT=	GhostBSD
GH_PROJECT=	${PORTNAME}
GH_TAGNAME=	${PORTVERSION}
GH_COMMIT= 2105641
USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
#NO_BUILD=	yes
NO_STAGE=	yes
#PLIST_DIRS=	bin/pywarrior
#WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}

		
.include <bsd.port.mk>
