# Created by:	Eric Turgeon ericturgeon@ghostbsd.org
# Date created:	November 11 2013


PORTNAME=	networkmgr
PORTVERSION=	0.6
PORTREVISION=	0
CATEGORIES=	net-mgmt
MASTER_SITES=	https://github.com/GhostBSD/${PORTNAME}/archive/

MAINTAINER=	ericturgeon@ghostbsd.org
COMMENT=	GTK network manager.

LICENSE=	BSD

USE_GITHUB=	yes
GH_ACCOUNT=	GhostBSD
GH_PROJECT=	${PORTNAME}
GH_TAGNAME=	${PORTVERSION}
GH_COMMIT=	e3dd752
USE_PYTHON=	yes
USE_PYDISTUTILS=	yes



.include <bsd.port.mk>
